// <auto-generated />
using System;
using FunPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FunPortalDbContext))]
    partial class FunPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FunPortal.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Main St, Springfield",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            Phone = "555-0101"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Oak Ave, Riverside",
                            CreatedOn = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            Phone = "555-0102"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Pine Rd, Lakeside",
                            CreatedOn = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "555-0103"
                        });
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembershipId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.OrderItemLine", b =>
                {
                    b.Property<int>("OrderItemLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("OrderItemLines");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasDiscriminator<int>("ProductType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.ShippingSlip", b =>
                {
                    b.Property<int>("ShippingSlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShippingSlipId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("ShippingSlips");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Products.Book", b =>
                {
                    b.HasBaseType("FunPortal.Domain.Entities.Products.Product");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "The Girl on the Train",
                            Price = 14.99m,
                            ProductType = 1,
                            Author = "Paula Hawkins",
                            ISBN = "978-1594633669"
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clean Code",
                            Price = 42.99m,
                            ProductType = 1,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350884"
                        });
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Products.MembershipProduct", b =>
                {
                    b.HasBaseType("FunPortal.Domain.Entities.Products.Product");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembershipType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            ProductId = 5,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Book Club Membership",
                            Price = 49.99m,
                            ProductType = 3,
                            DurationMonths = 12,
                            MembershipType = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Video Club Membership",
                            Price = 59.99m,
                            ProductType = 3,
                            DurationMonths = 12,
                            MembershipType = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Premium Membership",
                            Price = 99.99m,
                            ProductType = 3,
                            DurationMonths = 12,
                            MembershipType = 3
                        });
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Products.Video", b =>
                {
                    b.HasBaseType("FunPortal.Domain.Entities.Products.Product");

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            ProductId = 3,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Comprehensive First Aid Training",
                            Price = 19.99m,
                            ProductType = 2,
                            Director = "Medical Training Corp",
                            DurationMinutes = 120
                        },
                        new
                        {
                            ProductId = 4,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Advanced Programming Techniques",
                            Price = 29.99m,
                            ProductType = 2,
                            Director = "Tech Academy",
                            DurationMinutes = 180
                        });
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.Membership", b =>
                {
                    b.HasOne("FunPortal.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.OrderItemLine", b =>
                {
                    b.HasOne("FunPortal.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FunPortal.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("ItemLines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("FunPortal.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.ShippingSlip", b =>
                {
                    b.HasOne("FunPortal.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FunPortal.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("FunPortal.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("ItemLines");
                });
#pragma warning restore 612, 618
        }
    }
}
